---
title: Workopolis
timezone: UTC
destination: _site/
baseurl:
assetsurl: /static-assets/
collections:
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
name: portfolio
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
- src
- README.md
- Gemfile
- Gemfile.lock
port: 4000
sass:
  style: :compressed
